name: Trdl releaser
on:
  push:
    branches:
    - main

jobs:
  release:
    name: Perform release using trdl server
    runs-on: ubuntu-latest
    steps:

    - uses: werf/release-please-action@v99.0.0
      id: release
      with:
        release-type: simple
        # bump-minor-pre-major: yes
